version: '3'
services:
  telegraf:
    image: telegraf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - type: bind
        source: ./conf/telegraf.conf
        target: /etc/telegraf/telegraf.conf
    environment: 
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=MyInitialAdminToken0==
      - DOCKER_INFLUXDB_INIT_ORG=myorg 
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    restart: on-failure
    depends_on:
      - influxdb
    networks:
     - services_net 

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - influxdb2_data:/var/lib/influxdb2
    environment: 
       # Use these same configurations parameters in your telegraf configuration, telegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME_FILE=/run/secrets/influxdb2-admin-username
      - DOCKER_INFLUXDB_INIT_PASSWORD_FILE=/run/secrets/influxdb2-admin-password
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=/run/secrets/influxdb2-admin-token
      - DOCKER_INFLUXDB_INIT_ORG=myorg 
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    restart: on-failure
    networks:
      - services_net

  emqx:
    image: emqx/emqx:4.3.8
    logging:
      driver: "json-file"
      options: 
        max-size: "10m"
        max-file: "1"
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    restart: on-failure
    networks:
      - services_net

  smart_control_api:
    image: smart_control_api:latest
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ports:
      - "5000:5000"
    restart: on-failure
    networks:
      - services_net

secrets:
  influxdb2-admin-username:
    file: /env/influxdb2-admin-username
  influxdb2-admin-password:
    file: /env/influxdb2-admin-password
  influxdb2-admin-token:
    file: /env/influxdb2-admin-token

volumes:
  influxdb2_data:
  emqx_data:
  emqx_log:
networks:
  services_net:
    driver: overlay
  
